DEFAULT_DATABASE_PATH = "activities.csv"
DEFAULT_SORT_BY = "ld"
DEFAULT_TIMEDELTA_FORMAT = "hm"
DEFAULT_DATETIME_FORMAT = "%Y-%m-%d %H:%M:%S"

NUM_SECONDS_IN_MINUTE = 60
NUM_MINUTES_IN_HOUR = 60
NUM_HOURS_IN_DAY = 24
NUM_SECONDS_IN_HOUR = NUM_SECONDS_IN_MINUTE * NUM_MINUTES_IN_HOUR
NUM_SECONDS_IN_DAY = NUM_SECONDS_IN_HOUR * NUM_HOURS_IN_DAY
