#!/usr/bin/env python3

from datetime import datetime
import os

DATABASE_PATH = "activities.csv"
DATETIME_FORMAT = "%Y-%m-%d %H:%M:%S"

if not os.path.exists(DATABASE_PATH):
    with open(DATABASE_PATH, "w") as f:
        f.write("started,finished,activity\n")
activity = input("activity name? ")
started = datetime.now()
print("activity {} started".format(activity))
input("press enter to finish")
finished = datetime.now()
print("activity {} finished".format(activity))
with open(DATABASE_PATH, "a") as f:
    f.write(
        "{},{},{}\n".format(
            started.strftime(DATETIME_FORMAT),
            finished.strftime(DATETIME_FORMAT),
            activity
        )
    )
